import type { ScanReport } from "@/types/report";

export const allbirdsReport: ScanReport = {
  id: "demo-allbirds",
  url: "allbirds.com",
  scannedAt: "2026-02-23T14:15:00Z",
  overallScore: 81,
  grade: "B",
  verdict:
    "Your site is mostly ready for personal AI agents. Minor friction points in filtering and checkout form fields may cause some drop-offs.",
  comparison: "You're in the top 25% of ecommerce sites we've scanned",
  estimatedScoreAfterFixes: 94,
  categories: [
    {
      id: "discoverability",
      name: "Discoverability",
      weight: 0.15,
      score: 85,
      grade: "A",
      summary: "Clean navigation structure. Agents can find products within 2 clicks.",
      agentsCovered: ["browser", "accessibility"],
    },
    {
      id: "product-understanding",
      name: "Product Understanding",
      weight: 0.25,
      score: 90,
      grade: "A",
      summary: "Excellent structured data. Full Product schema with variants and reviews.",
      agentsCovered: ["browser", "data", "accessibility"],
    },
    {
      id: "navigation-interaction",
      name: "Navigation & Interaction",
      weight: 0.2,
      score: 72,
      grade: "B",
      summary: "Most interactions work. Color selector uses custom swatches that lack ARIA labels.",
      agentsCovered: ["browser", "accessibility"],
    },
    {
      id: "cart-checkout",
      name: "Cart & Checkout",
      weight: 0.25,
      score: 75,
      grade: "B",
      summary: "Guest checkout available. Some checkout form fields use non-standard autocomplete attributes.",
      agentsCovered: ["browser", "data", "accessibility"],
    },
    {
      id: "performance-resilience",
      name: "Performance & Resilience",
      weight: 0.1,
      score: 80,
      grade: "B",
      summary: "Fast load times (2.1s). No bot blocking. Minor JS dependency for product images.",
      agentsCovered: ["browser", "data"],
    },
    {
      id: "data-standards",
      name: "Data Standards & Feeds",
      weight: 0.05,
      score: 90,
      grade: "A",
      summary: "Comprehensive Schema.org, Open Graph, JSON-LD. Shopify product API accessible.",
      agentsCovered: ["data"],
    },
  ],
  journeys: [
    {
      agentType: "browser",
      agentName: "Browser Agent",
      agentDescription: "Navigates your site like a personal AI agent — clicking, scrolling, filling forms.",
      overallResult: "partial",
      narrative:
        "I was sent to buy sustainable sneakers from allbirds.com. The experience was mostly smooth — clean navigation, fast page loads, and guest checkout available. I got tripped up by color swatches that lacked ARIA labels (I had to guess which color I was selecting) and a checkout form field that used a custom dropdown for state selection. Overall, very close to agent-ready.",
      steps: [
        {
          stepNumber: 1,
          action: "Navigate to homepage",
          description: "Loading allbirds.com",
          result: "pass",
          narration: "allbirds.com loaded in 2.1 seconds. Clean layout with clear product categories visible. Minimal cookie banner at the bottom that didn't block interaction.",
          thought: "Clean site. Let me find sustainable sneakers.",
          cursorTarget: { x: 30, y: 15 },
          duration: 2100,
        },
        {
          stepNumber: 2,
          action: "Navigate to shoes category",
          description: "Clicking through to men's shoes",
          result: "pass",
          narration: "Navigation menu is keyboard-accessible and renders in the DOM without hover. I clicked 'Men' > 'Shoes' and reached the category page in two clicks. Each product card is a proper anchor link.",
          thought: "Navigation works well. Heading to shoes.",
          cursorTarget: { x: 25, y: 10 },
          duration: 1800,
        },
        {
          stepNumber: 3,
          action: "Select product",
          description: "Clicking on the Tree Runner",
          result: "pass",
          narration: "I selected the 'Tree Runner' — Allbirds' most popular shoe. Product page loaded with full details: price ($98), description, materials, and size options.",
          thought: "Tree Runner at $98. Good choice. Selecting size.",
          cursorTarget: { x: 35, y: 40 },
          duration: 2200,
        },
        {
          stepNumber: 4,
          action: "Select color",
          description: "Attempting to pick a color variant",
          result: "partial",
          narration: "The color selector uses custom swatch elements. They look like colored circles but lack aria-label attributes. I clicked the third swatch but couldn't confirm which color I selected until the product image updated. An agent without visual context would be guessing.",
          thought: "Color swatches have no labels. I'll click one and hope.",
          cursorTarget: { x: 45, y: 55 },
          duration: 1500,
        },
        {
          stepNumber: 5,
          action: "Select size and add to cart",
          description: "Selecting size US 10 and adding to cart",
          result: "pass",
          narration: "Size selector uses accessible button elements with clear labels. Selected US 10, clicked 'Add to Cart'. Cart slide-out confirmed: Tree Runner, Size 10, $98.",
          thought: "Size selection worked perfectly. Added to cart.",
          cursorTarget: { x: 50, y: 70 },
          duration: 1200,
        },
        {
          stepNumber: 6,
          action: "Proceed to checkout",
          description: "Navigating to checkout page",
          result: "pass",
          narration: "Clicked 'Checkout'. Guest checkout is available — no account required. The checkout form loaded with standard fields for email, shipping address, and payment.",
          thought: "Guest checkout available. Filling in details.",
          cursorTarget: { x: 50, y: 30 },
          duration: 1800,
        },
        {
          stepNumber: 7,
          action: "Fill checkout form",
          description: "Completing checkout fields",
          result: "partial",
          narration: "Most form fields are standard HTML inputs with autocomplete attributes. However, the state/province selector uses a custom dropdown component instead of a native <select>. I managed to interact with it but it took extra time to find the listbox role.",
          thought: "Custom state dropdown. Not ideal but I can work with it.",
          cursorTarget: { x: 50, y: 65 },
          duration: 3200,
        },
      ],
    },
    {
      agentType: "data",
      agentName: "Data Agent",
      agentDescription: "Reads structured data, APIs, and feeds to understand your product catalog.",
      overallResult: "pass",
      narrative:
        "Allbirds has excellent structured data. Full Product schema with variants, pricing, and reviews. As a Shopify store, the /products.json API is accessible, giving agents programmatic access to the entire catalog. robots.txt allows all major AI user agents.",
      steps: [
        {
          stepNumber: 1,
          action: "Parse structured data",
          description: "Extracting JSON-LD from product page",
          result: "pass",
          narration: "Found comprehensive JSON-LD Product schema: name, description, price, availability, 6 images, AggregateRating (4.5/5 from 12,300 reviews), and variant offers for all sizes.",
          thought: "Excellent structured data. Variants included.",
          duration: 400,
        },
        {
          stepNumber: 2,
          action: "Check product API",
          description: "Testing Shopify product API endpoint",
          result: "pass",
          narration: "Shopify /products.json endpoint is accessible. Returns full product catalog with variants, inventory levels, and images. /products/tree-runner.json returns individual product data.",
          thought: "Shopify API is open. Full catalog access.",
          duration: 600,
        },
        {
          stepNumber: 3,
          action: "Validate robots.txt and sitemap",
          description: "Checking AI agent access",
          result: "pass",
          narration: "robots.txt allows all major AI user agents (GPTBot, ClaudeBot, PerplexityBot). Sitemap includes 450+ product URLs with last-modified dates.",
          thought: "No restrictions on AI agents. Good.",
          duration: 300,
        },
      ],
    },
    {
      agentType: "accessibility",
      agentName: "Accessibility Agent",
      agentDescription: "Uses the accessibility tree and ARIA labels to interact with your site.",
      overallResult: "partial",
      narrative:
        "Allbirds has good accessibility foundations. Navigation, size selection, and add-to-cart all work through the accessibility tree. The main gaps are unlabeled color swatches and a custom state dropdown in checkout that lacks proper listbox semantics.",
      steps: [
        {
          stepNumber: 1,
          action: "Test navigation a11y",
          description: "Navigating via accessibility tree",
          result: "pass",
          narration: "Navigation menus are fully accessible with proper ARIA roles. All category links are in the DOM and keyboard-navigable.",
          thought: "Navigation is accessible. Good structure.",
          duration: 800,
        },
        {
          stepNumber: 2,
          action: "Test product page a11y",
          description: "Checking interactive elements",
          result: "partial",
          narration: "Size buttons have proper aria-labels. Add to Cart button is well-labeled. However, color swatches are div elements with background-color styling but no aria-label — I can't determine which color each swatch represents.",
          thought: "Color swatches need aria-labels.",
          duration: 600,
        },
        {
          stepNumber: 3,
          action: "Test checkout a11y",
          description: "Checking checkout form accessibility",
          result: "partial",
          narration: "Form inputs have labels and autocomplete attributes. The custom state/province dropdown announces as a text field rather than a listbox, making selection unintuitive for accessibility-based navigation.",
          thought: "State dropdown has wrong ARIA role.",
          duration: 900,
        },
      ],
    },
  ],
  findings: [
    {
      id: "f1",
      severity: "high",
      category: "navigation-interaction",
      title: "Color swatches lack ARIA labels",
      whatHappened: "Product color selectors are visual-only swatch elements (colored divs) with no aria-label or aria-description. An agent cannot determine which color each swatch represents.",
      whyItMatters: "When a personal agent is told 'buy me the black ones,' it can't identify which swatch to click. It must guess or skip color selection entirely, risking ordering the wrong color.",
      affectedAgents: [
        { name: "Browser Agent", impact: "degraded" },
        { name: "Accessibility Agent", impact: "blocked" },
      ],
      fix: {
        summary: "Add aria-label to each color swatch element.",
        technicalDetail: "Each color swatch div should have role='radio' (within a role='radiogroup'), aria-label with the color name, and aria-checked to indicate selection state.",
        codeSnippet: '<div role="radiogroup" aria-label="Select Color">\n  <div\n    role="radio"\n    aria-label="Natural Black"\n    aria-checked="true"\n    tabindex="0"\n    class="color-swatch"\n  />\n  <div\n    role="radio"\n    aria-label="Natural White"\n    aria-checked="false"\n    tabindex="-1"\n    class="color-swatch"\n  />\n</div>',
        effortEstimate: "1-2 hours",
      },
      priority: 1,
      effort: "low",
      estimatedPointsGain: 6,
    },
    {
      id: "f2",
      severity: "medium",
      category: "cart-checkout",
      title: "Custom state dropdown in checkout lacks proper semantics",
      whatHappened: "The state/province field in checkout uses a custom dropdown that announces as a text field. Selecting a state requires typing and hoping for autocomplete rather than browsing a proper listbox.",
      whyItMatters: "Agents that fill forms using accessibility APIs may fail to select the correct state, causing checkout errors or abandoned purchases.",
      affectedAgents: [
        { name: "Browser Agent", impact: "degraded" },
        { name: "Accessibility Agent", impact: "degraded" },
      ],
      fix: {
        summary: "Use a native <select> element or add proper combobox ARIA pattern.",
        technicalDetail: "Replace the custom dropdown with a native <select> element for state selection, or implement the ARIA combobox pattern with role='combobox', aria-expanded, and role='listbox' for options.",
        effortEstimate: "1-2 hours",
      },
      priority: 2,
      effort: "low",
      estimatedPointsGain: 4,
    },
    {
      id: "f3",
      severity: "low",
      category: "performance-resilience",
      title: "Product images require JavaScript to display",
      whatHappened: "Product images are lazy-loaded via JavaScript. Without JS execution, only placeholder elements are visible in the DOM.",
      whyItMatters: "Data Agents that parse raw HTML without JS rendering won't see product images. This is a minor issue since Schema.org markup includes image URLs, but it reduces graceful degradation.",
      affectedAgents: [
        { name: "Data Agent", impact: "fallback-available" },
      ],
      fix: {
        summary: "Add noscript fallback images or use native lazy loading.",
        technicalDetail: "Replace custom JS lazy loading with native loading='lazy' attribute on <img> elements, which ensures images are in the DOM for non-JS parsers.",
        effortEstimate: "1 hour",
      },
      priority: 3,
      effort: "low",
      estimatedPointsGain: 2,
    },
  ],
  actionPlan: [
    {
      findingId: "f1",
      title: "Add ARIA labels to color swatches",
      severity: "high",
      effort: "low",
      estimatedPointsGain: 6,
      isQuickWin: true,
    },
    {
      findingId: "f2",
      title: "Fix state dropdown in checkout",
      severity: "medium",
      effort: "low",
      estimatedPointsGain: 4,
      isQuickWin: true,
    },
    {
      findingId: "f3",
      title: "Use native image lazy loading",
      severity: "low",
      effort: "low",
      estimatedPointsGain: 2,
      isQuickWin: true,
    },
  ],
};
