import type { ScanReport } from "@/types/report";

export const amazonReport: ScanReport = {
  id: "demo-amazon",
  url: "amazon.com",
  scannedAt: "2026-02-22T09:00:00Z",
  overallScore: 89,
  grade: "A",
  verdict:
    "Your site is highly agent-ready. Personal AI agents can successfully discover, evaluate, and purchase products with minimal friction.",
  comparison: "You're in the top 5% of ecommerce sites we've scanned",
  estimatedScoreAfterFixes: 96,
  categories: [
    {
      id: "discoverability",
      name: "Discoverability",
      weight: 0.15,
      score: 92,
      grade: "A",
      summary: "Excellent search and navigation. Products findable in 1-2 steps.",
      agentsCovered: ["browser", "accessibility"],
    },
    {
      id: "product-understanding",
      name: "Product Understanding",
      weight: 0.25,
      score: 95,
      grade: "A",
      summary: "Rich structured data with full variant information. Best-in-class product schema.",
      agentsCovered: ["browser", "data", "accessibility"],
    },
    {
      id: "navigation-interaction",
      name: "Navigation & Interaction",
      weight: 0.2,
      score: 82,
      grade: "B",
      summary: "Most interactions work. Some filter widgets use complex JS components.",
      agentsCovered: ["browser", "accessibility"],
    },
    {
      id: "cart-checkout",
      name: "Cart & Checkout",
      weight: 0.25,
      score: 88,
      grade: "A",
      summary: "Guest checkout available. One-click ordering detectable. Cart API accessible.",
      agentsCovered: ["browser", "data", "accessibility"],
    },
    {
      id: "performance-resilience",
      name: "Performance & Resilience",
      weight: 0.1,
      score: 85,
      grade: "A",
      summary: "Fast load times. Some CAPTCHA on rapid interactions but not on normal flow.",
      agentsCovered: ["browser", "data"],
    },
    {
      id: "data-standards",
      name: "Data Standards & Feeds",
      weight: 0.05,
      score: 95,
      grade: "A",
      summary: "Full Schema.org, OG tags, comprehensive sitemap, product advertising API.",
      agentsCovered: ["data"],
    },
  ],
  journeys: [
    {
      agentType: "browser",
      agentName: "Browser Agent",
      agentDescription: "Navigates your site like a personal AI agent — clicking, scrolling, filling forms.",
      overallResult: "pass",
      narrative:
        "I was sent to buy wireless earbuds on amazon.com. The experience was smooth — search returned highly relevant results, product pages have comprehensive information, and guest checkout works. The only friction was a complex filter sidebar with some inaccessible widgets and a brief CAPTCHA when I navigated too quickly between pages.",
      steps: [
        {
          stepNumber: 1,
          action: "Navigate to homepage",
          description: "Loading amazon.com",
          result: "pass",
          narration: "amazon.com loaded in 1.8 seconds. Prominent search bar at the top. Clean layout despite the dense content.",
          thought: "Fast load. Search bar is front and center.",
          cursorTarget: { x: 50, y: 8 },
          duration: 1800,
        },
        {
          stepNumber: 2,
          action: "Search for product",
          description: "Typing 'wireless earbuds' in search",
          result: "pass",
          narration: "Typed 'wireless earbuds' in the search bar. Autocomplete suggestions appeared immediately. Search results loaded with 10,000+ results, well-organized with product cards showing price, rating, Prime badge, and delivery date.",
          thought: "Great search results. Very relevant.",
          cursorTarget: { x: 50, y: 8 },
          duration: 2200,
        },
        {
          stepNumber: 3,
          action: "Select product",
          description: "Clicking on top-rated earbuds",
          result: "pass",
          narration: "Selected the top result — Sony WF-1000XM5. Product page is extremely detailed: price ($228), 4.6/5 stars from 15,000+ reviews, full specifications, comparison table, and Q&A section. All content is in the DOM.",
          thought: "Comprehensive product page. All data accessible.",
          cursorTarget: { x: 40, y: 35 },
          duration: 2500,
        },
        {
          stepNumber: 4,
          action: "Select variant and add to cart",
          description: "Choosing color and adding to cart",
          result: "pass",
          narration: "Color options (Black, Silver) are proper button elements with aria-labels. Selected 'Black'. Clicked 'Add to Cart' — clear, prominent button. Cart confirmation showed correct item.",
          thought: "Color and add-to-cart work perfectly.",
          cursorTarget: { x: 60, y: 55 },
          duration: 1400,
        },
        {
          stepNumber: 5,
          action: "Proceed to checkout",
          description: "Navigating to checkout",
          result: "pass",
          narration: "Clicked 'Proceed to checkout'. Guest checkout option available ('Buy without signing in'). Checkout form uses standard HTML elements with proper autocomplete attributes.",
          thought: "Guest checkout works. Form fields are standard.",
          cursorTarget: { x: 50, y: 40 },
          duration: 1600,
        },
      ],
    },
    {
      agentType: "data",
      agentName: "Data Agent",
      agentDescription: "Reads structured data, APIs, and feeds to understand your product catalog.",
      overallResult: "pass",
      narrative:
        "Amazon has best-in-class structured data. Full Product schema with variants, reviews, and pricing. The Product Advertising API provides programmatic access. Sitemap is comprehensive. All AI user agents are allowed.",
      steps: [
        {
          stepNumber: 1,
          action: "Parse structured data",
          description: "Extracting JSON-LD and microdata",
          result: "pass",
          narration: "Rich JSON-LD Product schema with: name, brand, price, availability, AggregateRating, review count, images (8), GTIN/ASIN identifiers, and full variant offers.",
          thought: "Best structured data I've seen. Everything is here.",
          duration: 350,
        },
        {
          stepNumber: 2,
          action: "Check API access",
          description: "Testing Product Advertising API",
          result: "pass",
          narration: "Amazon Product Advertising API v5 is available for registered partners. Provides search, product details, prices, and availability programmatically.",
          thought: "Full API access for partners.",
          duration: 500,
        },
        {
          stepNumber: 3,
          action: "Validate robots.txt",
          description: "Checking AI agent permissions",
          result: "pass",
          narration: "robots.txt allows GPTBot, ClaudeBot, and most AI user agents on product pages. Blocks admin and checkout paths appropriately.",
          thought: "AI agents welcomed on product pages.",
          duration: 200,
        },
      ],
    },
    {
      agentType: "accessibility",
      agentName: "Accessibility Agent",
      agentDescription: "Uses the accessibility tree and ARIA labels to interact with your site.",
      overallResult: "partial",
      narrative:
        "Amazon's core shopping flow is accessible — search, product selection, cart, and checkout all work through the accessibility tree. The main gaps are in the filter sidebar, which uses complex nested widgets that are hard to navigate programmatically, and some product comparison tables that lack proper table semantics.",
      steps: [
        {
          stepNumber: 1,
          action: "Test search and navigation",
          description: "Using accessibility tree to search and navigate",
          result: "pass",
          narration: "Search input is well-labeled. Results are structured as a list. Each product card has accessible name, price, and rating information.",
          thought: "Search flow is fully accessible.",
          duration: 700,
        },
        {
          stepNumber: 2,
          action: "Test product page interaction",
          description: "Selecting variants and adding to cart",
          result: "pass",
          narration: "Color buttons have aria-labels. Add to Cart button is prominent in the accessibility tree. Quantity selector uses a native select element.",
          thought: "Product page a11y is strong.",
          duration: 500,
        },
        {
          stepNumber: 3,
          action: "Test filter sidebar",
          description: "Attempting to use category filters",
          result: "partial",
          narration: "Filter sidebar has many nested expandable sections. Some filter options (price range, brand checkboxes) work but the star rating filter uses a custom widget without proper ARIA semantics.",
          thought: "Filter sidebar is complex. Rating filter not accessible.",
          duration: 1200,
        },
      ],
    },
  ],
  findings: [
    {
      id: "f1",
      severity: "medium",
      category: "navigation-interaction",
      title: "Filter sidebar uses complex inaccessible widgets",
      whatHappened: "The search results filter sidebar has nested expandable sections with custom range sliders and star rating filters that lack proper ARIA roles.",
      whyItMatters: "Agents that need to filter large result sets (e.g., 'find me earbuds under $100 with 4+ stars') can't use these filters and must scan all results instead.",
      affectedAgents: [
        { name: "Accessibility Agent", impact: "degraded" },
        { name: "Browser Agent", impact: "degraded" },
      ],
      fix: {
        summary: "Add proper ARIA roles to filter widgets, especially star rating and price range.",
        technicalDetail: "The star rating filter should use role='radiogroup' with role='radio' for each star level. Price range should use role='slider' with proper aria-valuemin/max/now.",
        effortEstimate: "2-3 hours",
      },
      priority: 1,
      effort: "medium",
      estimatedPointsGain: 4,
    },
    {
      id: "f2",
      severity: "low",
      category: "performance-resilience",
      title: "CAPTCHA triggers on rapid page navigation",
      whatHappened: "When navigating between 5+ pages within 10 seconds, a CAPTCHA challenge appeared. Normal browsing speed did not trigger it.",
      whyItMatters: "Personal agents that browse quickly may hit CAPTCHAs, interrupting the shopping flow. However, this only affects unusually fast navigation patterns.",
      affectedAgents: [
        { name: "Browser Agent", impact: "degraded" },
      ],
      fix: {
        summary: "Consider raising the CAPTCHA threshold for non-suspicious navigation patterns.",
        technicalDetail: "Current threshold triggers at 5+ page loads in 10 seconds. Consider raising to 10+ or implementing more nuanced bot detection that distinguishes between shopping agents and scrapers.",
        effortEstimate: "2-4 hours",
      },
      priority: 2,
      effort: "medium",
      estimatedPointsGain: 3,
    },
  ],
  actionPlan: [
    {
      findingId: "f1",
      title: "Add ARIA roles to filter widgets",
      severity: "medium",
      effort: "medium",
      estimatedPointsGain: 4,
      isQuickWin: false,
    },
    {
      findingId: "f2",
      title: "Adjust CAPTCHA thresholds",
      severity: "low",
      effort: "medium",
      estimatedPointsGain: 3,
      isQuickWin: false,
    },
  ],
};
