/**
 * Cleanup Cascade Entries — Remove false changelog entries caused by
 * the robots.txt cascade bug.
 *
 * The bug: when robots.txt fetch failed (timeout, 5xx, etc.), the scanner
 * incorrectly set `found: false` and all agents to `no_rule`, generating
 * up to 10+ false entries per brand per incident. The scanner code is now
 * fixed, but historical entries remain in the DB.
 *
 * Detection heuristics:
 *   1. Per-brand cascade: multiple entries for the same brand on the same
 *      day where agents changed to "no_rule" AND/OR robots.txt presence
 *      changed to "false"/"0".
 *   2. Volume anomaly: days where >20% of brands had the same field
 *      change — indicates a scanner outage, not real policy changes.
 *
 * Usage:
 *   Dry run:  npx tsx scripts/cleanup-cascade-entries.ts
 *   Delete:   npx tsx scripts/cleanup-cascade-entries.ts --delete
 */

import { execSync } from "child_process";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const dbPath = path.join(__dirname, "..", "data", "arc-score.db");

const deleteMode = process.argv.includes("--delete");

// ─── SQLite helper ─────────────────────────────────────────────────

function query<T = Record<string, string>>(sql: string): T[] {
  const result = execSync(
    `sqlite3 -json "${dbPath}" "${sql.replace(/"/g, '\\"')}"`,
    { encoding: "utf-8", maxBuffer: 10 * 1024 * 1024 },
  ).trim();
  if (!result) return [];
  return JSON.parse(result) as T[];
}

function exec(sql: string): void {
  execSync(
    `sqlite3 "${dbPath}" "${sql.replace(/"/g, '\\"')}"`,
    { encoding: "utf-8" },
  );
}

// ─── Tracked agents (match changelog-engine.ts) ────────────────────

const ROBOTS_TXT_AGENTS = [
  "GPTBot", "ChatGPT-User", "ClaudeBot", "Claude-Web",
  "PerplexityBot", "Google-Extended", "CCBot", "Amazonbot",
  "Bingbot",
];

// Fields that can be generated by the cascade bug.
// The DB uses two naming conventions depending on when the entry was created:
//   - "agent_access_GPTBot" (from agent status diff engine)
//   - "GPTBot robots.txt" (from robots.txt rule diff engine)
//   - "robots.txt presence" (scalar diff)
const CASCADE_FIELDS = new Set([
  ...ROBOTS_TXT_AGENTS.map(a => `agent_access_${a}`),
  ...ROBOTS_TXT_AGENTS.map(a => `${a} robots.txt`),
  "robots.txt presence",
]);

// ─── Types ─────────────────────────────────────────────────────────

interface ChangelogRow {
  id: string;
  brand_id: string;
  field: string;
  old_value: string | null;
  new_value: string | null;
  detected_at: string;
}

interface BrandRow {
  id: string;
  slug: string;
  name: string;
}

// ─── Load data ─────────────────────────────────────────────────────

console.log("Scanning for cascade artifacts...\n");

// Get total brand count for volume anomaly threshold
const brandCountRow = query<{ cnt: string }>(
  "SELECT count(*) AS cnt FROM brands WHERE active = 1",
);
const totalBrands = parseInt(brandCountRow[0]?.cnt ?? "0", 10);
console.log(`Total active brands: ${totalBrands}`);

// Load all changelog entries
const allEntries = query<ChangelogRow>(
  "SELECT id, brand_id, field, old_value, new_value, detected_at FROM changelog_entries ORDER BY detected_at, brand_id",
);
console.log(`Total changelog entries: ${allEntries.length}\n`);

// Load brand lookup (sqlite3 -json returns id as number; coerce to string for consistent map keys)
const brandRows = query<BrandRow>("SELECT id, slug, name FROM brands");
const brandMap = new Map<string, BrandRow>();
for (const b of brandRows) {
  brandMap.set(String(b.id), b);
}

// ─── Heuristic 1: Per-brand cascade detection ─────────────────────
// A cascade incident = same brand, same day, has entries changing to
// "no_rule" for agent fields AND/OR "robots.txt presence" -> "false".
// If a brand has 3+ such entries on one day, it's almost certainly
// a cascade artifact.

const CASCADE_THRESHOLD = 3; // min cascade entries per brand per day

// Group entries by brand + date
type BrandDateKey = string; // `${brand_id}::${date}`

function dateOf(detectedAt: string): string {
  // detected_at is ISO or datetime — take the date portion
  return detectedAt.slice(0, 10);
}

function isCascadeEntry(e: ChangelogRow): boolean {
  if (!CASCADE_FIELDS.has(e.field)) return false;

  // Agent field (agent_access_* or "* robots.txt") changing to "no_rule"
  if (
    (e.field.startsWith("agent_access_") || e.field.endsWith(" robots.txt")) &&
    e.new_value === "no_rule"
  ) return true;

  // robots.txt presence changing to false/0
  if (e.field === "robots.txt presence" && (e.new_value === "false" || e.new_value === "0")) return true;

  return false;
}

const brandDateGroups = new Map<BrandDateKey, ChangelogRow[]>();

for (const entry of allEntries) {
  if (!isCascadeEntry(entry)) continue;
  const key: BrandDateKey = `${String(entry.brand_id)}::${dateOf(entry.detected_at)}`;
  let group = brandDateGroups.get(key);
  if (!group) {
    group = [];
    brandDateGroups.set(key, group);
  }
  group.push(entry);
}

const cascadeIds = new Set<string>();

for (const [, entries] of brandDateGroups) {
  if (entries.length >= CASCADE_THRESHOLD) {
    for (const e of entries) {
      cascadeIds.add(e.id);
    }
  }
}

// ─── Heuristic 2: Volume anomaly detection ─────────────────────────
// Days where >20% of brands changed the same field.

const VOLUME_ANOMALY_THRESHOLD = 0.20;

// Group by date + field, count distinct brands
const dateFieldBrands = new Map<string, Set<string>>(); // `${date}::${field}` -> brand_ids
const dateFieldEntries = new Map<string, ChangelogRow[]>();

for (const entry of allEntries) {
  const key = `${dateOf(entry.detected_at)}::${entry.field}`;
  let brands = dateFieldBrands.get(key);
  if (!brands) {
    brands = new Set();
    dateFieldBrands.set(key, brands);
  }
  brands.add(String(entry.brand_id));

  let entries = dateFieldEntries.get(key);
  if (!entries) {
    entries = [];
    dateFieldEntries.set(key, entries);
  }
  entries.push(entry);
}

const volumeAnomalyIds = new Set<string>();
const volumeAnomalies: Array<{ date: string; field: string; brandCount: number; pct: string }> = [];

for (const [key, brands] of dateFieldBrands) {
  const brandCount = brands.size;
  const rate = totalBrands > 0 ? brandCount / totalBrands : 0;
  if (rate > VOLUME_ANOMALY_THRESHOLD) {
    const sepIdx = key.indexOf("::");
    const date = key.slice(0, sepIdx);
    const field = key.slice(sepIdx + 2);
    volumeAnomalies.push({
      date,
      field,
      brandCount,
      pct: `${(rate * 100).toFixed(1)}%`,
    });
    // Mark all entries for this date+field as anomalous
    const entries = dateFieldEntries.get(key) ?? [];
    for (const e of entries) {
      volumeAnomalyIds.add(e.id);
    }
  }
}

// ─── Merge results ─────────────────────────────────────────────────

const allFlaggedIds = new Set([...cascadeIds, ...volumeAnomalyIds]);

// Build the display list from the flagged entries
const flaggedEntries = allEntries.filter(e => allFlaggedIds.has(e.id));

// ─── Print results ─────────────────────────────────────────────────

const line = "─".repeat(72);

// Print volume anomalies
if (volumeAnomalies.length > 0) {
  console.log(line);
  console.log("  VOLUME ANOMALIES (>20% of brands changed same field on same day)");
  console.log(line);
  for (const a of volumeAnomalies) {
    console.log(`  ${a.date}  ${a.field}  (${a.brandCount} brands = ${a.pct})`);
  }
  console.log();
}

// Print per-brand cascade groups
const cascadeGroupCount = [...brandDateGroups.entries()].filter(
  ([, entries]) => entries.length >= CASCADE_THRESHOLD,
).length;

if (cascadeGroupCount > 0) {
  console.log(line);
  console.log(`  CASCADE CLUSTERS (${CASCADE_THRESHOLD}+ no_rule/false entries per brand per day)`);
  console.log(line);

  let shown = 0;
  for (const [key, entries] of brandDateGroups) {
    if (entries.length < CASCADE_THRESHOLD) continue;
    const [brandId, date] = key.split("::");
    const brand = brandMap.get(brandId);
    const label = brand ? brand.slug : `brand-${brandId}`;

    // Show first 50 clusters in detail, then summarize
    if (shown < 50) {
      console.log(`\n  ${label} (${date}) — ${entries.length} entries:`);
      for (const e of entries) {
        console.log(`    ${e.field}: ${e.old_value ?? "null"} -> ${e.new_value ?? "null"}`);
      }
    }
    shown++;
  }

  if (shown > 50) {
    console.log(`\n  ... and ${shown - 50} more cascade clusters (not shown)`);
  }
  console.log();
}

// Print individual entries from volume anomaly that aren't in cascade clusters
const volumeOnlyIds = [...volumeAnomalyIds].filter(id => !cascadeIds.has(id));
if (volumeOnlyIds.length > 0) {
  console.log(line);
  console.log("  VOLUME-ANOMALY-ONLY ENTRIES (not part of a cascade cluster)");
  console.log(line);

  const volumeOnlyEntries = allEntries.filter(e => volumeOnlyIds.includes(e.id));
  let shown = 0;
  for (const e of volumeOnlyEntries) {
    if (shown >= 100) {
      console.log(`  ... and ${volumeOnlyEntries.length - 100} more (not shown)`);
      break;
    }
    const brand = brandMap.get(String(e.brand_id));
    const label = brand ? brand.slug : `brand-${e.brand_id}`;
    console.log(`  ${dateOf(e.detected_at)}  ${label}  ${e.field}: ${e.old_value ?? "null"} -> ${e.new_value ?? "null"}`);
    shown++;
  }
  console.log();
}

// ─── Summary ───────────────────────────────────────────────────────

console.log(line);
console.log("  SUMMARY");
console.log(line);
console.log(`  Cascade cluster entries:       ${cascadeIds.size}`);
console.log(`  Volume anomaly entries:        ${volumeAnomalyIds.size}`);
console.log(`  Total flagged (deduplicated):  ${allFlaggedIds.size}`);
console.log(`  Total changelog entries in DB: ${allEntries.length}`);
console.log();

// ─── Delete if requested ───────────────────────────────────────────

if (allFlaggedIds.size === 0) {
  console.log("No cascade artifacts found. Database is clean.\n");
  process.exit(0);
}

if (!deleteMode) {
  console.log("Dry run complete. To delete these entries, run:");
  console.log("  npx tsx scripts/cleanup-cascade-entries.ts --delete\n");
  process.exit(0);
}

// Delete in batches of 500 (SQLite has a variable limit)
const idsToDelete = [...allFlaggedIds];
const BATCH_SIZE = 500;
let deleted = 0;

for (let i = 0; i < idsToDelete.length; i += BATCH_SIZE) {
  const batch = idsToDelete.slice(i, i + BATCH_SIZE);
  const idList = batch.join(",");
  exec(`DELETE FROM changelog_entries WHERE id IN (${idList})`);
  deleted += batch.length;
}

console.log(`Deleted ${deleted} cascade artifact entries from changelog_entries.\n`);

// Verify
const remaining = query<{ cnt: string }>(
  "SELECT count(*) AS cnt FROM changelog_entries",
);
console.log(`Remaining changelog entries: ${remaining[0]?.cnt ?? "?"}\n`);
